create table "public"."Allergene" (
    "lmiv_id" bigint generated by default as identity not null,
    "Allergene_name" text default ''::text,
    "Allergene_discription" text default ''::text
);


alter table "public"."Allergene" enable row level security;

create table "public"."User" (
    "User_id" bigint generated by default as identity not null,
    "E-Mail-Adresse" text,
    "Passwort" text,
    "Vorname" text,
    "Nachname" text,
    "Hauptmensa" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."User" enable row level security;

create table "public"."Zutaten" (
    "Zutat_id" bigint generated by default as identity not null,
    "Zutat_name" text not null default ''::text,
    "Zutat_kcal" text default ''::text,
    "Zutat_carbs" text default ''::text,
    "Zutat_protein" text default ''::text,
    "Zutat_fats" text default ''::text,
    "Allergne_id" bigint
);


alter table "public"."Zutaten" enable row level security;

create table "public"."ZutatenAllergene" (
    "Zutaten_id" bigint generated by default as identity not null,
    "lmiv_id" bigint not null,
    "istEnthalten" boolean,
    "kannSpurenEnthalten" boolean
);


alter table "public"."ZutatenAllergene" enable row level security;

CREATE UNIQUE INDEX "Allergene_pkey" ON public."Allergene" USING btree (lmiv_id);

CREATE UNIQUE INDEX "User_pkey" ON public."User" USING btree ("User_id");

CREATE UNIQUE INDEX "ZutatenAllergene_pkey" ON public."ZutatenAllergene" USING btree ("Zutaten_id", lmiv_id);

CREATE UNIQUE INDEX "Zutaten_pkey" ON public."Zutaten" USING btree ("Zutat_id");

alter table "public"."Allergene" add constraint "Allergene_pkey" PRIMARY KEY using index "Allergene_pkey";

alter table "public"."User" add constraint "User_pkey" PRIMARY KEY using index "User_pkey";

alter table "public"."Zutaten" add constraint "Zutaten_pkey" PRIMARY KEY using index "Zutaten_pkey";

alter table "public"."ZutatenAllergene" add constraint "ZutatenAllergene_pkey" PRIMARY KEY using index "ZutatenAllergene_pkey";

alter table "public"."ZutatenAllergene" add constraint "ZutatenAllergene_Zutaten_id_fkey" FOREIGN KEY ("Zutaten_id") REFERENCES "Zutaten"("Zutat_id") not valid;

alter table "public"."ZutatenAllergene" validate constraint "ZutatenAllergene_Zutaten_id_fkey";

alter table "public"."ZutatenAllergene" add constraint "ZutatenAllergene_lmiv_id_fkey" FOREIGN KEY (lmiv_id) REFERENCES "Allergene"(lmiv_id) not valid;

alter table "public"."ZutatenAllergene" validate constraint "ZutatenAllergene_lmiv_id_fkey";

grant delete on table "public"."Allergene" to "anon";

grant insert on table "public"."Allergene" to "anon";

grant references on table "public"."Allergene" to "anon";

grant select on table "public"."Allergene" to "anon";

grant trigger on table "public"."Allergene" to "anon";

grant truncate on table "public"."Allergene" to "anon";

grant update on table "public"."Allergene" to "anon";

grant delete on table "public"."Allergene" to "authenticated";

grant insert on table "public"."Allergene" to "authenticated";

grant references on table "public"."Allergene" to "authenticated";

grant select on table "public"."Allergene" to "authenticated";

grant trigger on table "public"."Allergene" to "authenticated";

grant truncate on table "public"."Allergene" to "authenticated";

grant update on table "public"."Allergene" to "authenticated";

grant delete on table "public"."Allergene" to "service_role";

grant insert on table "public"."Allergene" to "service_role";

grant references on table "public"."Allergene" to "service_role";

grant select on table "public"."Allergene" to "service_role";

grant trigger on table "public"."Allergene" to "service_role";

grant truncate on table "public"."Allergene" to "service_role";

grant update on table "public"."Allergene" to "service_role";

grant delete on table "public"."User" to "anon";

grant insert on table "public"."User" to "anon";

grant references on table "public"."User" to "anon";

grant select on table "public"."User" to "anon";

grant trigger on table "public"."User" to "anon";

grant truncate on table "public"."User" to "anon";

grant update on table "public"."User" to "anon";

grant delete on table "public"."User" to "authenticated";

grant insert on table "public"."User" to "authenticated";

grant references on table "public"."User" to "authenticated";

grant select on table "public"."User" to "authenticated";

grant trigger on table "public"."User" to "authenticated";

grant truncate on table "public"."User" to "authenticated";

grant update on table "public"."User" to "authenticated";

grant delete on table "public"."User" to "service_role";

grant insert on table "public"."User" to "service_role";

grant references on table "public"."User" to "service_role";

grant select on table "public"."User" to "service_role";

grant trigger on table "public"."User" to "service_role";

grant truncate on table "public"."User" to "service_role";

grant update on table "public"."User" to "service_role";

grant delete on table "public"."Zutaten" to "anon";

grant insert on table "public"."Zutaten" to "anon";

grant references on table "public"."Zutaten" to "anon";

grant select on table "public"."Zutaten" to "anon";

grant trigger on table "public"."Zutaten" to "anon";

grant truncate on table "public"."Zutaten" to "anon";

grant update on table "public"."Zutaten" to "anon";

grant delete on table "public"."Zutaten" to "authenticated";

grant insert on table "public"."Zutaten" to "authenticated";

grant references on table "public"."Zutaten" to "authenticated";

grant select on table "public"."Zutaten" to "authenticated";

grant trigger on table "public"."Zutaten" to "authenticated";

grant truncate on table "public"."Zutaten" to "authenticated";

grant update on table "public"."Zutaten" to "authenticated";

grant delete on table "public"."Zutaten" to "service_role";

grant insert on table "public"."Zutaten" to "service_role";

grant references on table "public"."Zutaten" to "service_role";

grant select on table "public"."Zutaten" to "service_role";

grant trigger on table "public"."Zutaten" to "service_role";

grant truncate on table "public"."Zutaten" to "service_role";

grant update on table "public"."Zutaten" to "service_role";

grant delete on table "public"."ZutatenAllergene" to "anon";

grant insert on table "public"."ZutatenAllergene" to "anon";

grant references on table "public"."ZutatenAllergene" to "anon";

grant select on table "public"."ZutatenAllergene" to "anon";

grant trigger on table "public"."ZutatenAllergene" to "anon";

grant truncate on table "public"."ZutatenAllergene" to "anon";

grant update on table "public"."ZutatenAllergene" to "anon";

grant delete on table "public"."ZutatenAllergene" to "authenticated";

grant insert on table "public"."ZutatenAllergene" to "authenticated";

grant references on table "public"."ZutatenAllergene" to "authenticated";

grant select on table "public"."ZutatenAllergene" to "authenticated";

grant trigger on table "public"."ZutatenAllergene" to "authenticated";

grant truncate on table "public"."ZutatenAllergene" to "authenticated";

grant update on table "public"."ZutatenAllergene" to "authenticated";

grant delete on table "public"."ZutatenAllergene" to "service_role";

grant insert on table "public"."ZutatenAllergene" to "service_role";

grant references on table "public"."ZutatenAllergene" to "service_role";

grant select on table "public"."ZutatenAllergene" to "service_role";

grant trigger on table "public"."ZutatenAllergene" to "service_role";

grant truncate on table "public"."ZutatenAllergene" to "service_role";

grant update on table "public"."ZutatenAllergene" to "service_role";


